### ISSUE TITLE
error

### ISSUE THREAD

**Issue by justynpride** [hutman/c56dropzone#2]
Just discovered this feature, and thought it would be helpful on an old site I still maintain. I get the following when I go to the multiple file uploader:

<img width="573" alt="Screenshot 2022-10-23 at 08 27 05" src="https://user-images.githubusercontent.com/309050/197379765-4afbc47a-e08a-441b-896d-168faa8721f1.png">

The three folders and contents are in the root of the public_html folder.

**Comment by hutbert** [comment]
Contribution from ktarsov should resolve this
